# Generated by Django 4.2 on 2024-04-29 23:05

import business.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.chargingstation')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_date', models.DateTimeField(auto_now=True)),
                ('expiry_date', models.DateTimeField(blank=True)),
                ('sub_code', models.CharField(blank=True, default=business.models.generate_verification_code, max_length=300, null=True)),
                ('usage', models.PositiveIntegerField(blank=True, default=0)),
                ('day_usage', models.PositiveIntegerField(blank=True, default=0)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.customer')),
            ],
        ),
    ]
