# Generated by Django 4.2 on 2024-04-29 23:24

import business.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_chargingstation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersubscription',
            name='sub_code',
            field=models.CharField(blank=True, default=business.models.generate_verification_code, editable=False, max_length=300, null=True, unique=True),
        ),
    ]
