# Generated by Django 4.2 on 2024-04-29 23:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_alter_customersubscription_sub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersubscription',
            name='sub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
