# Generated by Django 4.2 on 2024-05-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_alter_customersubscription_sub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
