# Generated by Django 4.2 on 2024-05-01 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_chargingmonitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_code', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('device', models.CharField(blank=True, max_length=30, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.customer')),
            ],
        ),
        migrations.DeleteModel(
            name='ChargingMonitor',
        ),
    ]
