# Generated by Django 4.2 on 2024-05-01 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_chargingactivity_delete_chargingmonitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='business.chargingstation'),
        ),
    ]
