# Generated by Django 4.2 on 2024-05-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_alter_customer_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingactivity',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
