# Generated by Django 4.2 on 2024-05-01 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_chargingactivity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingactivity',
            name='sub_code',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
