# Generated by Django 4.2 on 2024-05-01 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_alter_chargingactivity_sub_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chargingactivity',
            options={'verbose_name_plural': 'Charging Activities'},
        ),
        migrations.RenameField(
            model_name='chargingactivity',
            old_name='customer',
            new_name='subscriber',
        ),
    ]
