# Generated by Django 4.2 on 2024-05-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_alter_chargingactivity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingactivity',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
