# Generated by Django 4.2 on 2024-05-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_chargingactivity_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
