# Generated by Django 4.2 on 2024-05-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_chargingstation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='stations'),
        ),
    ]
