# Generated by Django 4.2 on 2024-05-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_customersubscription_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersubscription',
            name='status',
            field=models.CharField(blank=True, choices=[(0, 'Not charging'), (1, 'Charging'), (2, 'Charged')], default='Not charging', max_length=10, null=True),
        ),
    ]
