# Generated by Django 4.2.3 on 2024-07-06 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0021_alter_customersubscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customersubscription',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='business.customer'),
        ),
        migrations.AlterField(
            model_name='customersubscription',
            name='status',
            field=models.CharField(blank=True, choices=[(0, 'Not charging'), (1, 'Charging'), (2, 'Charged')], default=(1, 'Charging'), max_length=10, null=True),
        ),
    ]
